# Generated by Django 2.1.7 on 2019-06-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versus', models.PositiveSmallIntegerField()),
                ('avg_age', models.SmallIntegerField()),
                ('location', models.CharField(max_length=10)),
                ('hope_age', models.SmallIntegerField(default=None, null=True)),
                ('is_matched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
