# Generated by Django 2.1.7 on 2019-06-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20190612_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avg_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='hope_age',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='versus',
            field=models.IntegerField(),
        ),
    ]
