# Generated by Django 2.1.7 on 2019-06-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_auto_20190612_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
