# Generated by Django 2.1.7 on 2019-06-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='day',
            field=models.CharField(choices=[('월요일', 'mon'), ('화요일', 'tue'), ('수요일', 'wed'), ('목요일', 'thur'), ('금요일', 'fri'), ('토요일', 'sat'), ('일요일', 'sun')], default='sun', max_length=5),
            preserve_default=False,
        ),
    ]
