# Generated by Django 2.1.7 on 2019-05-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('team_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('team_type', models.PositiveSmallIntegerField(choices=[(2, '2명'), (3, '3명')], verbose_name='team type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
