# Generated by Django 2.1.5 on 2019-05-13 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='아이디')),
                ('email', models.CharField(max_length=100, verbose_name='이메일')),
                ('is_certificated', models.BooleanField(default=False, verbose_name='대학 인증')),
                ('is_matched', models.BooleanField(default=False, verbose_name='매칭 중')),
                ('is_warned', models.BooleanField(default=False, verbose_name='경고')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='정지 회원')),
                ('is_delete', models.BooleanField(default=False, verbose_name='삭제된 회원')),
                ('is_active', models.BooleanField(default=True, verbose_name='활동 회원')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저들',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', '남자'), ('F', '여자')], max_length=1)),
                ('univ', models.CharField(choices=[('Hanyang', '한양대학교'), ('Sejong', '세종대학교')], max_length=15)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('avatar', models.ImageField(upload_to='')),
                ('height', models.PositiveSmallIntegerField(null=True)),
                ('weight', models.PositiveSmallIntegerField(null=True)),
                ('religion', models.CharField(max_length=10)),
                ('isSmoker', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
