# Generated by Django 2.1.7 on 2019-05-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='서울시', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='성동구', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
