# Generated by Django 2.1.7 on 2019-06-12 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190531_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_matched',
            new_name='has_team',
        ),
        migrations.AddField(
            model_name='profile',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='_profile_follower_+', to='user.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_profile_following_+', to='user.Profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_profile',
            field=models.BooleanField(default=False, verbose_name='프로필 존재 여부'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='matching.Team'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='univ',
            field=models.CharField(choices=[('hanyang', '한양대학교'), ('sejong', '세종대학교'), ('kunkuk', '건국대학교')], max_length=15),
        ),
    ]
