# Generated by Django 2.1.7 on 2019-06-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190612_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follower',
            field=models.ManyToManyField(blank=True, default=None, related_name='_profile_follower_+', to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, default=None, related_name='_profile_following_+', to='user.Profile'),
        ),
    ]
